// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"name":"登录","path":"/user/login","parentId":"1","id":"2"},"3":{"name":"概况","icon":"smile","path":"/abstract","parentId":"ant-design-pro-layout","id":"3"},"4":{"name":"任务管理","icon":"table","path":"/task","parentId":"ant-design-pro-layout","id":"4"},"5":{"name":"任务详情","icon":"profile","path":"/taskdetail","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/","redirect":"/abstract","parentId":"ant-design-pro-layout","id":"6"},"7":{"path":"*","layout":false,"id":"7"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import( './EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__Abstract__index" */'@/pages/Abstract/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Task__index" */'@/pages/Task/index.tsx')),
'5': React.lazy(() => import(/* webpackChunkName: "p__TaskDetail__index" */'@/pages/TaskDetail/index.tsx')),
'6': React.lazy(() => import( './EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/home/guorenqi/wx_simulation/frontend/src/.umi/plugin-layout/Layout.tsx')),
},
  };
}
