// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/home/guorenqi/wx_simulation/frontend/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TableOutlined from '/home/guorenqi/wx_simulation/frontend/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/TableOutlined';
import ProfileOutlined from '/home/guorenqi/wx_simulation/frontend/node_modules/.pnpm/@ant-design+icons@4.8.1_react-dom@18.2.0_react@18.2.0/node_modules/@ant-design/icons/es/icons/ProfileOutlined';
export default { SmileOutlined, TableOutlined, ProfileOutlined };
